spring:
  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest
  datasource:
    password: root123
    url: jdbc:postgresql://localhost:5432/prolancerdb
    username: postgres
    driver-class-name: org.postgresql.Driver
  jackson:
    serialization:
      fail-on-empty-beans: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        #        generate_statistics: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  security:
    jwt:
      secret-key: AFE7ADB55DC317701A6E48476CF5290F51C05B59A38E35016EAEC6708333C548
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
#application:
#  minio:
#    applicationName: online-banking
#    host: http://localhost:9001
#    username: b@nking
#    password: b@nkingp@$$word
server:
  port: 8080





#logging:
#  file:
#    name: prolancer.log
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE